---
- name: required packages
  apt:
    name:
    - xscreensaver
    - xscreensaver-gl
    - xscreensaver-gl-extra
    - miscfiles
    - lightdm
    - fluxbox
    - xserver-xorg
    - x11-xserver-utils
    - mpv
  tags:
  - client

- name: config lightdm
  lineinfile: dest=/etc/lightdm/lightdm.conf
    insertafter='^\[Seat' line='{{item}}'
  loop:
  - autologin-user=blabgen
  - autologin-user-timeout=5
  tags:
  - client
  - client2

- name: create dirs
  file: path={{item}} state=directory
  loop:
  - "{{user_dir}}/.fluxbox"
  - "{{user_dir}}/bin"
  - "{{user_dir}}/log"
  - "{{user_dir}}/run"
  tags:
  - client

- name: copy user files
  copy: src=../{{item.src}} dest={{user_dir}}/{{item.dst}}
  loop:
  - src: client/.xsession
    dst: .xsession
  - src: client/.fluxbox/keys
    dst: .fluxbox/keys
  tags:
  - client

- name: copy movie cmd
  copy: src=../client/xs_movie dest={{user_dir}}/bin/xs_movie mode=0755
  tags:
  - client
  - client3
- name: movie dir
  file: path={{user_dir}}/movies state=directory
  tags:
  - client
  - client3

  #######################################################
- name: setup server name
  template: src=url.j2 dest={{user_dir}}/url
  tags:
  - client

- name: setup proxy vars
  template: src=proxy.j2 dest={{user_dir}}/proxy
  tags:
  - client

- name: copy scripts
  template: src=../{{item}} dest={{user_dir}}/bin mode=0755
  loop:
  - check_kiosk
  - daily_adm
  tags:
  - client

  #######################################################
- name: remove check daemon
  cron: job={{user_dir}}/bin/check_kiosk minute=*/10
    name='blabgen kiosk watchdog' state=absent
  tags:
  - client

- name: remove daily admin script
  cron: job={{user_dir}}/bin/daily_adm hour=6 minute=5
    name='blabgen kiosk admin' state=absent
  tags:
  - client

- name: add daily admin script
  cron: job={{user_dir}}/bin/daily_adm hour=6 minute=5
    cron_file=blabgen user=root
    name='blabgen kiosk admin'
  tags:
  - client
