#!/bin/sh

# change the sudo row if this cron job is running as root

logfile=/home/blabgen/log/check_kiosk.log
lockfile=/home/blabgen/run/check_kiosk.pid

touch $logfile
########################

find_icew() {
	ps cax|grep icew|sed 's/.* //'
}

check_lock() {
	if [ -e $lockfile ]; then
		pid=`cat $lockfile`
		if kill -0 $pid; then
			# process still running
			exit 0
		fi
	fi
	echo $$ > $lockfile
}

########################

check_lock

while true; do
	if [ "`find_icew`" = iceweasel ]; then
		sleep 10
		continue
	fi

	# this cron job runs as a non-root, change here if necessary
	sudo /usr/sbin/service lightdm restart
	date '+%F %T kiosk restarted' >> $logfile
	sleep 20
done
