---
- name: install blabgen
  hosts: servers
  sudo_user: "{{my_sudo_user}}"
  sudo: yes

  roles:
  - install
# enable this if the blabgen user and group are not created
#  - user

- name: install blabgen client
  hosts: clients
  sudo_user: "{{my_sudo_user}}"
  sudo: yes
  roles:
  - client
