---
- name: install blabgen
  hosts: servers
  become_user: "{{my_sudo_user}}"
  become: yes

  roles:
  - install
# enable this if the blabgen user and group are not created
#  - user

- name: install blabgen client
  hosts: clients
  become_user: "{{my_sudo_user}}"
  become: yes
  roles:
  - client
